const CALCULATOR_CONST_DEFINITIONS = [
  {
    id: 'bank-value',
    label: 'Bank Value Calculation',
    sourceTab: 'Bank value calculation',
    fields: [
      {
        key: 'baseEquity',
        label: 'Base Equity',
        description: 'Fixed baseline equity used in step A.',
        defaultValue: 100,
        min: 0,
        step: 0.01,
      },
      {
        key: 'financialMultiplier',
        label: 'Financial Multiplier',
        description: 'Multiplier that converts nominal growth into asset value.',
        defaultValue: 2.71,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultDividendPct',
        label: 'Default Dividend %',
        description: 'Default starting value for average dividend percentage input.',
        defaultValue: 4,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultRealGrowth',
        label: 'Default Real Growth',
        description: 'Default FOMC long-term real growth input.',
        defaultValue: 1.9,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultPceIndex',
        label: 'Default PCE Index',
        description: 'Default average quarterly PCE index input.',
        defaultValue: 2.9,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultInterestRate',
        label: 'Default Interest Rate',
        description: 'Default Machete-derived interest input.',
        defaultValue: 4.93,
        min: 0,
        step: 0.01,
      },
    ],
  },
  {
    id: 'inflation',
    label: 'Calculating Inflation',
    sourceTab: 'Calculating inflation',
    fields: [
      {
        key: 'fixedRiskPremium',
        label: 'Fixed Risk Premium',
        description: 'Step 1 fixed risk premium value.',
        defaultValue: 1.5,
        min: 0,
        step: 0.01,
      },
      {
        key: 'biasElement1',
        label: 'Bias Element 1',
        description: 'Lower limit of known bias from research.',
        defaultValue: 0.15,
        min: 0,
        step: 0.01,
      },
      {
        key: 'biasElement2',
        label: 'Bias Element 2',
        description: 'Upper limit of known bias from research.',
        defaultValue: 0.4,
        min: 0,
        step: 0.01,
      },
      {
        key: 'biasElement3',
        label: 'Bias Element 3',
        description: 'Custom model bias component.',
        defaultValue: 0,
        min: 0,
        step: 0.01,
      },
      {
        key: 'numberOfElements',
        label: 'Number Of Elements',
        description: 'Element count used in average bias formula.',
        defaultValue: 3,
        min: 1,
        step: 1,
        integer: true,
      },
      {
        key: 'probabilityBiasUpDown',
        label: 'Probability Bias Up/Down',
        description: 'Probability multiplier applied to average bias.',
        defaultValue: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
      },
      {
        key: 'defaultPrimeRate',
        label: 'Default Prime Rate',
        description: 'Default Prime Rate input value.',
        defaultValue: 6.75,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultFedFundsRate',
        label: 'Default Fed Funds Rate',
        description: 'Default Fed Funds Rate input value.',
        defaultValue: 3.64,
        min: 0,
        step: 0.01,
      },
    ],
  },
  {
    id: 'market-value',
    label: 'Market Value Of Tradable Shares',
    sourceTab: 'Market value of tradable shares',
    fields: [
      {
        key: 'timeRoot250Days',
        label: 'Time Root (250 Days)',
        description: 'Square root of 250 trading days.',
        defaultValue: 15.81,
        min: 0,
        step: 0.01,
      },
      {
        key: 'govActivityCoefficient',
        label: 'Government Activity Coefficient',
        description: 'Multiplier used in debt-to-GDP transformation.',
        defaultValue: 2.5,
        min: 0,
        step: 0.01,
      },
      {
        key: 'hundredPercent',
        label: '100 Percent Constant',
        description: 'Base percent constant used in expected return formula.',
        defaultValue: 100,
        min: 1,
        step: 1,
      },
      {
        key: 'defaultCorporateEquities',
        label: 'Default Corporate Equities',
        description: 'Default Corporate Equities input value.',
        defaultValue: 47185,
        min: 0,
        step: 1,
      },
      {
        key: 'defaultCurrentGDP',
        label: 'Default Current GDP',
        description: 'Default Current GDP input value.',
        defaultValue: 31442,
        min: 0.0001,
        step: 1,
      },
      {
        key: 'defaultMarketableTreasuryDebt',
        label: 'Default Marketable Treasury Debt',
        description: 'Default Marketable Treasury Debt input value.',
        defaultValue: 29299,
        min: 0,
        step: 1,
      },
      {
        key: 'defaultFederalBudgetDeficit',
        label: 'Default Federal Budget Deficit',
        description: 'Default Federal Budget Deficit input value.',
        defaultValue: 1853,
        min: 0,
        step: 1,
      },
      {
        key: 'defaultInflationFromPrime',
        label: 'Default Inflation From Prime',
        description: 'Default inflation-from-prime input value.',
        defaultValue: 1.61,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultMovingAverageDJIA',
        label: 'Default Moving Average DJIA',
        description: 'Default moving average DJIA input value.',
        defaultValue: 48000,
        min: 0,
        step: 1,
      },
    ],
  },
  {
    id: 'machete',
    label: 'Machete Macroeconomic Risk',
    sourceTab: 'Machete',
    fields: [
      {
        key: 'toCalculateDebtRatio',
        label: 'To Calculate Debt Ratio Constant',
        description: 'Fixed coefficient used to calculate debt ratio.',
        defaultValue: 2.5,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultPublicDebt',
        label: 'Default Public Debt',
        description: 'Default Public Debt parameter value.',
        defaultValue: 122.49,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultFinancialInflation',
        label: 'Default Financial Inflation',
        description: 'Default Financial Inflation parameter value.',
        defaultValue: 2.9,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultAssetPrice',
        label: 'Default Asset Price',
        description: 'Default market price of a theoretical asset.',
        defaultValue: 120,
        min: 0.01,
        step: 0.01,
      },
    ],
  },
  {
    id: 'market-indices',
    label: 'Market Indices Forecast',
    sourceTab: 'Market indices',
    fields: [
      {
        key: 'naturalNumberE',
        label: 'Natural Number e Constant',
        description: 'Coefficient of equilibrium constant e.',
        defaultValue: 2.71,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultMarketableAssets',
        label: 'Default Marketable Assets',
        description: 'Default Total marketable financial assets parameter value.',
        defaultValue: 93900.00,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultGDP',
        label: 'Default Current GDP',
        description: 'Default Current GDP parameter value.',
        defaultValue: 31442,
        min: 0.01,
        step: 0.01,
      },
      {
        key: 'defaultDjiaMovingAverage',
        label: 'Default DJIA Moving Average',
        description: 'Default DJIA moving average rate for the previous quarter.',
        defaultValue: 48321,
        min: 0,
        step: 0.01,
      },
    ],
  },
  {
    id: 'long-term-return',
    label: 'Long-Term Investor Return',
    sourceTab: 'Long-term investor return',
    fields: [
      {
        key: 'fixedFinancialCoefficient',
        label: 'Fixed Financial Coefficient',
        description: 'Fixed coefficient multiplying nominal growth (row 11).',
        defaultValue: 2.71,
        min: 0,
        step: 0.01,
      },
      {
        key: 'riskFactor',
        label: 'Risk Factor',
        description: 'Divisor risk factor for the investor return after risk (row 14).',
        defaultValue: 180,
        min: 1,
        step: 1,
        integer: true,
      },
      {
        key: 'anchorYear',
        label: 'Anchor Year',
        description: 'The historic low anchor year (row 33).',
        defaultValue: 1932,
        min: 1800,
        max: 2100,
        step: 1,
        integer: true,
      },
      {
        key: 'djiaValue1932',
        label: 'DJIA Value in 1932',
        description: 'The historical DJIA value in 1932 (row 48).',
        defaultValue: 44,
        min: 0.01,
        step: 0.01,
      },
      {
        key: 'inflationBias',
        label: 'Inflation Bias Limit',
        description: 'Inflation bias increment for Step 3 scenarios (row 58/62).',
        defaultValue: 0.1,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultRealGrowth',
        label: 'Default Real Growth',
        description: 'Default value for long-term real growth input.',
        defaultValue: 1.8,
        min: -100,
        max: 100,
        step: 0.01,
      },
      {
        key: 'defaultInflation',
        label: 'Default Inflation',
        description: 'Default value for PCE index average inflation input.',
        defaultValue: 2.8,
        min: -100,
        max: 100,
        step: 0.01,
      },
      {
        key: 'defaultCurrentYear',
        label: 'Default Current Year',
        description: 'Default value for current year calculation input.',
        defaultValue: 2026,
        min: 1800,
        max: 2100,
        step: 1,
        integer: true,
      },
    ],
  },
  {
    id: 'quick-risk-return',
    label: 'Quick Risk Return',
    sourceTab: 'Quick risk return',
    fields: [
      {
        key: 'debtRatioCoeff',
        label: 'Debt Ratio Coefficient',
        description: 'Coefficient of real government activity (row 11).',
        defaultValue: 2.5,
        min: 0,
        step: 0.01,
      },
      {
        key: 'debtRatioDivisor',
        label: 'Debt Ratio Divisor',
        description: 'Divisor used to calculate debt ratio percentage (row 14).',
        defaultValue: 100,
        min: 1,
        step: 1,
        integer: true,
      },
      {
        key: 'complete100',
        label: 'Complete 100 Constant',
        description: 'Numerator constant used to calculate Borto\'s risk-free return (row 20).',
        defaultValue: 100,
        min: 1,
        step: 1,
        integer: true,
      },
      {
        key: 'inflationBias',
        label: 'Inflation Bias Limit',
        description: 'Inflation bias increment for Step 2 bounds (row 49/53).',
        defaultValue: 0.1,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultPublicDebt',
        label: 'Default Public Debt',
        description: 'Default public debt percentage input.',
        defaultValue: 122.49,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultInflationFromPrime',
        label: 'Default Inflation (Prime)',
        description: 'Default inflation derived from prime input.',
        defaultValue: 1.61,
        min: -100,
        max: 100,
        step: 0.01,
      },
      {
        key: 'defaultDjiaStart',
        label: 'Default DJIA Beginning Year',
        description: 'Default value for DJIA beginning of a year input.',
        defaultValue: 46.053,
        min: 0.001,
        step: 0.001,
      },
    ],
  },
  {
    id: 'base-model',
    label: 'The Base Model',
    sourceTab: 'The base model',
    fields: [
      {
        key: 'governmentActivityLeverage',
        label: 'Government Activity Leverage',
        description: 'Leverage multiplier applied to Fed Debt (row 43).',
        defaultValue: 2.5,
        min: 0,
        step: 0.1,
      },
      {
        key: 'defaultM1',
        label: 'Default M1 (Money supply)',
        description: 'Default M1 money supply input in billions (row 10).',
        defaultValue: 19194,
        min: 0,
        step: 1,
      },
      {
        key: 'defaultM0',
        label: 'Default M0 (Liquidity programs)',
        description: 'Default M0 quantitative expansion input in billions (row 12).',
        defaultValue: 6632,
        min: 0,
        step: 1,
      },
      {
        key: 'defaultGdp',
        label: 'Default Current GDP',
        description: 'Default current GDP input in billions (row 15).',
        defaultValue: 31490,
        min: 1,
        step: 1,
      },
      {
        key: 'defaultSavings',
        label: 'Default Personal Savings',
        description: 'Default personal savings input in billions (row 18).',
        defaultValue: 841,
        min: 0,
        step: 1,
      },
      {
        key: 'defaultGrowth',
        label: 'Default Fed Median Growth',
        description: 'Default Fed annual growth estimate percentage input (row 32).',
        defaultValue: 2.4,
        min: -100,
        max: 100,
        step: 0.01,
      },
      {
        key: 'defaultDebt',
        label: 'Default Fed Debt',
        description: 'Default total public debt percentage input (row 41).',
        defaultValue: 122.49,
        min: 0,
        step: 0.01,
      },
      {
        key: 'defaultPce',
        label: 'Default PCE inflation',
        description: 'Default quarterly PCE inflation percentage input (row 46).',
        defaultValue: 2.9,
        min: -100,
        max: 100,
        step: 0.01,
      },
      {
        key: 'defaultDjiaStart',
        label: 'Default DJIA Start',
        description: 'Default DJIA value at beginning of the year input (row 63).',
        defaultValue: 48000,
        min: 1,
        step: 1,
      },
    ],
  },
];

function getCalculatorDefinitionById(calculatorId) {
  return CALCULATOR_CONST_DEFINITIONS.find((item) => item.id === calculatorId) || null;
}

function getCalculatorDefaults(calculatorId) {
  const definition = getCalculatorDefinitionById(calculatorId);
  if (!definition) {
    return {};
  }

  return definition.fields.reduce((acc, field) => {
    acc[field.key] = field.defaultValue;
    return acc;
  }, {});
}

export {
  CALCULATOR_CONST_DEFINITIONS,
  getCalculatorDefaults,
  getCalculatorDefinitionById,
};